services:
  - type: web
    name: white-canvas
    env: docker
    plan: free
    region: singapore # Change if needed
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false # You will fill this after deployment
      - key: DB_CONNECTION
        value: mysql
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: APP_KEY
        generateValue: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 25558
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.resend.com
      - key: MAIL_PORT
        value: 465
      - key: MAIL_USERNAME
        value: resend
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: ssl
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_UPLOAD_PRESET
        value: ml_default
